#version 460 core

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

#include "random"
#include "heightmaperosioncommon"
#line 7
float sinNoise(vec2 p) {
    return ( sin(p.x) * 0.5 + 0.5 + sin(p.y) * 0.5 + 0.5);
}

TerrainGenTileInfo init (uvec2 uvecpos) {
    vec2 p = vec2(uvecpos);
    vec2 uv = p / vec2(MAPSIZE);
    vec4 heights = vec4(0);

    TerrainGenTileInfo tile;
    heights[BEDROCK] = sin(p.x / 80.0) * 0.5 + 0.5 + cos(p.y / 60.0) * 0.5 + 0.5;

    float distanceFromCenter = distance(p,vec2(MAPSIZE/2));

    float distanceScale = distanceFromCenter / float(MAPSIZE/2);
    distanceScale *= distanceScale;
    distanceScale *= distanceScale;
    distanceScale *= distanceScale;
    distanceScale *= distanceScale;

    heights[BEDROCK] = abs(fbm(p / 700.0,25)) > mix(0.37,1.0,clamp(distanceScale * 1.0,0.0,1.0)) ? 0.5 : 0.5;

    uvec2 bedrockType = GRANITE;
    float gravelAmount = 2.0;

    float h = fbm(p / 2600.0 + vec2(123.0), 26) * 1450.0 - 500.0;

    h += 15.0;
    h += (1.0 - distanceFromCenter / float(MAPSIZE/2)) * (1.0 - distanceFromCenter / float(MAPSIZE/2)) * 25.0;

    heights[BEDROCK] *= h;
    heights[BEDROCK] -= 70.0;

    setSeed(gl_GlobalInvocationID.xy);
    heights[BEDROCK] += 1.0 + random() * 0.2;

    if (any(equal(gl_GlobalInvocationID.xy,uvec2(0))) || any(equal(gl_GlobalInvocationID.xy,uvec2(MAPSIZE - 1)))) {
        heights[LARGE] = 0.0;
        heights[BEDROCK] = 15.0;
    }

    if(true || heights[BEDROCK] > seaLevel) 
        heights[BEDROCK] += noise(p/100.0) * 2.0 + 2.0;

    heights[BEDROCK] = max(heights[BEDROCK],8.0);

    float water = 0.0;

    heights[LARGE] = gravelAmount;

    water = max(seaLevel-heights[BEDROCK]-heights[LARGE],0.0);
    water += 0.0;
    heights[BEDROCK] += random() * 0.1;

    tile.fluid = uvec4(0,0,0,floatBitsToUint(water));
    tile.prevFluid = uvec4(0,0,0,floatBitsToUint(water));
    tile.ground = uvec4(0);
    tile.ground[BEDROCK] = packGroundLayer(newGroundLayer(bedrockType.x,heights[BEDROCK]));
    tile.ground[LARGE]   = packGroundLayer(newGroundLayer(GRAVEL.x,heights[LARGE]));
    tile.ground[MEDIUM]  = packGroundLayer(newGroundLayer(GRAYSAND.x,heights[MEDIUM]));
    tile.ground[SMALL]   = packGroundLayer(newGroundLayer(SILT.x,heights[SMALL]));
    tile.velocity = vec2(0);
    tile.percentOut = vec4(0);

    return tile;
}

void main() {

    tiles[gl_GlobalInvocationID.x][gl_GlobalInvocationID.y] = init(gl_GlobalInvocationID.xy);
}